# Generated by Django 4.1.3 on 2022-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('task_status', models.CharField(choices=[('select', ''), ('pending', '1'), ('completed', '2')], default='2', max_length=20)),
            ],
        ),
    ]
